[package]
authors = ["Christopher Brickley <brickley@gmail.com>"]
description = "A rust crate for sending messages to Slack via webhooks."
homepage = "https://github.com/frostly/rust-slack"
keywords = ["slack", "webhook", "hook", "messaging"]
license = "MIT/Apache-2.0"
name = "slack-hook"
readme = "README.md"
repository = "https://github.com/frostly/rust-slack"
version = "0.6.0"

[dependencies]
chrono = "0.4"
reqwest = "0.7"
hex = "0.2.0"
error-chain = "~0.11"
serde = "1"
serde_derive = "1"
serde_json = "1"
url_serde = "0.2"
